[package]
name = "posixmq"
version = "0.1.0"
description = "An idiomatic posix message queue wrapper for Linux and FreeBSD with optional mio integration"
readme = "README.md"
repository = "https://github.com/tormol/posixmq"
license = "Apache-2.0 / MIT"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
keywords = ["posix", "mq", "mqueue", "queue"]
categories = ["os::unix-apis", "asynchronous"]
edition = "2018"

[dependencies]
libc = "0.2.35" # .35 added symbols for (Free|Net|Dragonfly)BSD
mio = {version = "0.6.14", optional=true} # .13 drags in libc 0.1 when built with -Z minimal-versions

[lib]
path = "posixmq.rs"

[[test]]
name = "test"
path = "tests.rs"

[package.metadata.docs.rs]
features = ["mio"]
