[package]
name = "posixmq"
version = "0.1.1"
description = "An idiomatic posix message queue wrapper with optional mio integration"
readme = "README.md"
repository = "https://github.com/tormol/posixmq"
license = "Apache-2.0 / MIT"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
keywords = ["posix", "mq", "mqueue", "queue"]
categories = ["os::unix-apis", "asynchronous"]
exclude = ["/tests/**", "/examples/**"] # contains more than just tests and examples
edition = "2018"

[dependencies]
libc = "0.2.59"
# 0.2.59 added mq_timed{send,receive}() and FIONCLEX for Linux and all mq_ functions for solarish
mio = {version = "0.6.14", optional=true}
# 0.6.13 drags in libc 0.1 when built with -Z minimal-versions

[lib]
path = "posixmq.rs"

[package.metadata.docs.rs]
features = ["mio"]
